### ISSUE TITLE
Cognitive game API support

### ISSUE THREAD

**Issue by etsardou** [rapp-project/rapp-api#11]
- [x] C++
- [x] JS
- [x] Python

@akintsakis please post the new service's specifications (if they have been finalized).

**Comment by etsardou** [comment]
These are ```cognitive_test_chooser``` and ```record_cognitive_test_performance```

**Comment by alexge233** [comment]
@etsardou all related issues such as  #10, #13, #14, #15 and #11 (this issue) will be implemented in the next upcoming version (0.6)

**Comment by etsardou** [comment]
Yes, I have already added them all to the 0.6 milestone. This release is planned for the end of January - begin of February.

**Comment by alexge233** [comment]
I haven't added examples, but the api is implemented (but untested). Closing for now, will test soon.
