### ISSUE TITLE
Text to speech API support

### ISSUE THREAD

**Issue by etsardou** [rapp-project/rapp-api#12]
- [x] C++
- [x] JS
- [x] Python

[Info](https://github.com/rapp-project/rapp-platform/wiki/RAPP-Text-to-speech-using-Espeak-&-Mbrola#input--output)

**Comment by alexge233** [comment]
@etsardou what's this? documentation or wiki?

**Comment by etsardou** [comment]
This refers to the text-to-speech node. Info [here](https://github.com/rapp-project/rapp-platform/wiki/RAPP-Text-to-speech-using-Espeak-&-Mbrola) (or click the "info" above)

**Comment by alexge233** [comment]
Please see [issue #233 on rapp-platform ](https://github.com/rapp-project/rapp-platform/issues/233) regarding this. We can't add base64 for raw audio data, please change to multiform/part as per the RFC standard.

**Comment by klpanagi** [comment]
Status update on JS API?
The text_to_speech RappCloud module exists [here](https://github.com/rapp-project/rapp-api/blob/ortelio/js/includes/cloud/text_to_speech.js).

**Comment by lpenteri** [comment]
Yes it is implemented where you pointed, I just forgot to check the checkbox.
