### ISSUE TITLE
Python tests migration

### ISSUE THREAD

**Issue by alexge233** [rapp-project/rapp-api#16]
@klpanagi could you please migrate the Python tests under the API? AFAIK they are currently under the platform.

**Comment by etsardou** [comment]
Actually that is not that easy since all the setup scripts and CI scripts have to change. I propose to revisit this in the next release (0.7).

**Comment by alexge233** [comment]
If this is an API test (unit test) it should be in there, if its a platform test, then let's move them all to the platform?

**Comment by etsardou** [comment]
Didn't get you. What you mean by "python tests"? If you mean [these](https://github.com/rapp-project/rapp-platform/tree/master/rapp_testing_tools), they are integration tests, as they test the API, the web services and the ROS background nodes.

**Comment by alexge233** [comment]
I thought we had python unit tests, never mind them, nothing to move to the api for python.
