### ISSUE TITLE
[C++]: Use CMAKE_INSTALL_PREFIX var to assign installation paths

### ISSUE THREAD

**Issue by klpanagi** [rapp-project/rapp-api#19]
Consider assigning installation paths using CMAKE_INSTALL_PREFIX argument to cmake to allow modifications through cmake's cli.

**Edit**
Consider this issue to be critical! It affects setup and installation of the rapp-robot-nao. Check related issue [here](https://github.com/rapp-project/rapp-robot-nao/issues/11)

**Comment by maciek-slon** [comment]
I've created proper fixes and additions in CMake files, and I'm ready to apply them. But, as there are two active branches with C++ changes in the rapp-api (ortelio and devel), I don't know which one to use as a base for C++ code changes. I've asked Alex twice (19/03 and 22/03) which one to use, but got no answer, thus the patch is still waiting.

**Comment by alexge233** [comment]
@klpanagi I will pass a CLI parameter to be used as the install directory for the libraries, and another for the headers, which will default to `/usr/local/` if nothing is passed.

@maciek-slon Please create a new branch `wut` and apply your changes there. We will merge once we've finished working on ortelio.

**Comment by maciek-slon** [comment]
Should we base on ortelio or devel? Which one is "better" C++ base?

**Comment by alexge233** [comment]
I don't know who owns and works on devel, ortelio will have our latest code but is not stable and will be changing significantly very soon. I would suggest you either clone ortelio and expect to have changes after, or wait until we do the move from HTTP to JSON.

**Comment by klpanagi** [comment]
@maciek-slon  I would suggest the following:

- Create a new branch having **api_stable** as parent
- Rebase to Ortelio to get the functionalities provided there.
- Continue developing under the newly created branch, lets say cpp/<feature>

**Comment by maciek-slon** [comment]
Unfortunatelly, rebasing to ortelio creates A LOT of conflicts in cpp/hpp files.

**Comment by alexge233** [comment]
Added feature and closing.
Can somebody please test the `-DOPEN_NAO=On` flag please?

**Comment by maciek-slon** [comment]
There is a typo in CMakeLists for OPEN_NAO: Line 180 should be 
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=gnu++11 -Wall -fPIC -static-libstdc++ -m32")
instead of 
set(CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS} "-std=gnu++11 -Wall -fPIC -static-libstdc++ -m32")
