### ISSUE TITLE
Inconsistency in Python API documentation for Google Speech detection

### ISSUE THREAD

**Issue by etsardou** [rapp-project/rapp-api#31]
https://github.com/rapp-project/rapp-api/blob/devel/python/RappCloud/CloudMsgs/README.md#speech-recognition-google

In response ```sentences``` or ```alternatives```?

**Comment by klpanagi** [comment]
Thanks for mentioning this @etsardou, the correct response key is `alternatives` 

Updated README.md file in `python` branch
