### ISSUE TITLE
Weather reporter Python API question

### ISSUE THREAD

**Issue by etsardou** [rapp-project/rapp-api#32]
https://github.com/rapp-project/rapp-api/blob/devel/python/RappCloud/CloudMsgs/README.md#weather-reporter---current-weather

What is metric and why it is Int? @athallas

**Comment by athallas** [comment]
Metric specifies the value units, i.e. Celsius/Fahrenheit etc. It is int because yweather required a boolean.

**Comment by etsardou** [comment]
What is True and what False?

**Comment by athallas** [comment]
True is metric(si) and false is us units.
