### ISSUE TITLE
Gitter badge wrong link 

### ISSUE THREAD

**Issue by athallas** [rapp-project/rapp-api#4]
The Gitter badge in the master branch points to the wrong link: [link](https://gitter.im/trogdoro/xiki?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

Also it seems misplaced, probably due to erroneous merging of the pull request.

**Comment by athallas** [comment]
Seems that the pull request has not been handled at all. I am reopening the pull request #3 to fix this issue.

**Comment by alexge233** [comment]
fixed
