### ISSUE TITLE
Token-based authentication

### ISSUE THREAD

**Issue by alexge233** [rapp-project/rapp-api#8]
@klpanagi 
Authentication (in C++) is hardcoded into qr_detection in [cpp/includes/cloud/qrDetector/qrDetector.hpp](https://github.com/rapp-project/rapp-api/blob/master/cpp/includes/cloud/qrDetector/qrDetector.hpp#L56).

If we need token-based authentication, it must be implemented across the API/Lanugages,
else this can be removed.

This has nothing to do with SSL/TLS https sockets which should be implemented in the next version.

**Comment by klpanagi** [comment]
We previously discussed on enhancing security, by using token-based authentication.

The approach is for the per-robot-platform Core Agent to hold the Platform Authentication tokens. This approach requires the RAPP-API to request authentication tokens from the core-agent and use em either on initialization or on each Platform Service Call.

@etsardou should we consider this under an upcoming milestone?

**Comment by alexge233** [comment]
I will freeze this for now, but I think we should use user tokens for identifying users on the platform.
